services:
  - type: web
    name: robo-school
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AdminKey
        sync: false
      - key: Email__Enabled
        value: "false"
      - key: Email__Host
        sync: false
      - key: Email__Port
        value: "587"
      - key: Email__Username
        sync: false
      - key: Email__Password
        sync: false
      - key: Email__FromEmail
        sync: false
      - key: Email__FromName
        value: ROBO.SCHOOL
      - key: Email__UseSsl
        value: "true"
